import Link from 'next/link';
import { PencilIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';
import type { Snapshot } from '@/lib/plan-review';
import { activityNames } from '@/lib/activity-plans';
import { Card, CardHeader, CardTitle, CardContent, CardAction } from '@/components/ui/card';
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell, TableFooter } from '@/components/ui/table';
const money=new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'});
export function ActivityReviewContent({snapshot, sbmcEditHref, tlmEditHref}:{snapshot:Snapshot; sbmcEditHref?:string; tlmEditHref?:string}){
 return <>{(['sbmc','tlm'] as const).map(key=>{const lines=snapshot[key];if(!lines)return null;const editHref=key==='sbmc'?sbmcEditHref:tlmEditHref;return <Card key={key} id={'review-'+key}><CardHeader><CardTitle>{key==='sbmc'?'SBMC':'Teaching & Learning Materials'}</CardTitle>{editHref&&<CardAction><Button asChild variant="outline" size="icon-lg" className="rounded-full"><Link href={editHref} aria-label={key==='sbmc'?'Edit SBMC':'Edit Teaching & Learning Materials'} title={key==='sbmc'?'Edit SBMC':'Edit Teaching & Learning Materials'}><PencilIcon data-icon="inline-start" /></Link></Button></CardAction>}</CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Activity / description</TableHead><TableHead>Strategy / target</TableHead><TableHead>Location</TableHead><TableHead>Quantity</TableHead><TableHead>Unit cost</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{lines.map(l=><TableRow key={l.id}><TableCell className="whitespace-normal"><strong>{activityNames[key][l.activity]}</strong><p>{l.description}</p>{l.equipment&&<p>{l.equipment}</p>}</TableCell><TableCell className="whitespace-normal">{l.strategy}<p>{l.target_group}</p></TableCell><TableCell>{l.location}</TableCell><TableCell>{l.quantity}</TableCell><TableCell>{money.format(Number(l.unit_cost))}</TableCell><TableCell>{money.format(Math.round(Number(l.unit_cost)*100)*l.quantity/100)}</TableCell></TableRow>)}{!lines.length&&<TableRow><TableCell colSpan={6}>No saved items.</TableCell></TableRow>}</TableBody><TableFooter><TableRow><TableCell colSpan={5}>Total</TableCell><TableCell>{money.format(lines.reduce((s,l)=>s+Math.round(Number(l.unit_cost)*100)*l.quantity,0)/100)}</TableCell></TableRow></TableFooter></Table>{key==='tlm'&&<div className="mt-5"><h3 className="mb-2 font-medium">Distribution list</h3><Table><TableHeader><TableRow><TableHead>School</TableHead><TableHead>LGA</TableHead><TableHead>Level</TableHead><TableHead>Location</TableHead></TableRow></TableHeader><TableBody>{snapshot.tlmDistribution?.map(s=><TableRow key={s.id}><TableCell>{s.name}</TableCell><TableCell>{s.lga}</TableCell><TableCell>{s.level}</TableCell><TableCell>{s.location}</TableCell></TableRow>)}{!snapshot.tlmDistribution?.length&&<TableRow><TableCell colSpan={4}>No distribution schools.</TableCell></TableRow>}</TableBody></Table></div>}</CardContent></Card>;})}</>;
}
