'use client';
import { useEffect,useState,useCallback,useRef,useId } from 'react';
import { AccessibilityIcon,ArrowLeftIcon,ArrowRightIcon,ChevronLeftIcon,ChevronRightIcon,PlusIcon,PencilIcon,Trash2Icon } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { ButtonGroup,ButtonGroupSeparator } from '@/components/ui/button-group';
import { Card,CardHeader,CardTitle,CardDescription,CardContent } from '@/components/ui/card';
import { Field,FieldGroup,FieldLabel,FieldSet,FieldLegend } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { CurrencyInput } from '@/components/currency-input';
import { Textarea } from '@/components/ui/textarea';
import { NativeSelect,NativeSelectOption } from '@/components/ui/native-select';
import { Checkbox } from '@/components/ui/checkbox';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Alert,AlertTitle,AlertDescription } from '@/components/ui/alert';
import { AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction } from '@/components/ui/alert-dialog';
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table';
import { Combobox,ComboboxInput,ComboboxContent,ComboboxEmpty,ComboboxList,ComboboxItem } from '@/components/ui/combobox';
import { currentPlanHref,planPeriod,type ActionPlan } from '@/lib/action-plans';
import { packageSchema,kindNames,modelNames,modelFor,strategies,auditGaps,calculateInfrastructure,packageProblem,type InfrastructureInput,type InfrastructureSchool,type InfrastructurePackage,type InfraDocument } from '@/lib/infrastructure-model';
import { InfrastructurePackageDetails } from '@/components/infrastructure-package-details';
import { InfrastructureIllustration } from '@/components/infrastructure-illustration';
import { FileUpload, DocumentFiles } from '@/components/document-files';
import { FieldHelp } from '@/components/field-help';
import './activity-plan-editor.css';
import './infrastructure-editor.css';
const money=new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN'});
type Data={plan:ActionPlan;schools:InfrastructureSchool[];packages:InfrastructurePackage[];documents:InfraDocument[];canEdit:boolean};
const blank=(kind:InfrastructureInput['kind'])=>packageSchema.parse({kind,schoolId:1,components:['Primary']});
const docLabels={drawings:'Drawings',boq:'Bill of Quantities',survey:'Geophysical survey report',land:'Land documentation',photo:'Photographic evidence'};
const docHelp:Partial<Record<InfraDocument['kind'],string>>={drawings:'Attach the infrastructure drawings shared across this funding plan.',boq:"Attach this school's detailed Bill of Quantities as an Excel workbook or PDF.",survey:"Attach this school's geophysical survey report.",land:'Attach proof of ownership, right of occupancy or a community agreement for this school.',photo:'Attach clear photographs showing the facilities being assessed.'};
const documentAccept:Record<InfraDocument['kind'],string>={drawings:'.pdf,.docx,.xlsx,.png,.jpg,.jpeg',boq:'.pdf,.xls,.xlsx',survey:'.pdf,.docx,.xlsx,.png,.jpg,.jpeg',land:'.pdf,.docx,.xlsx,.png,.jpg,.jpeg',photo:'.pdf,.docx,.xlsx,.png,.jpg,.jpeg'};
function SelectField({label,value,options,onChange,help}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void;help?:string}){
 const id=useId();return <Field><div className="flex items-center gap-1"><FieldLabel htmlFor={id}>{label}</FieldLabel>{help&&<FieldHelp>{help}</FieldHelp>}</div><NativeSelect id={id} aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><NativeSelectOption key={o.value} value={o.value}>{o.label}</NativeSelectOption>)}</NativeSelect></Field>;
}
function NumberField({label,value,onChange,step='1',help}:{label:string;value:number;onChange:(n:number)=>void;step?:string;help?:string}){const id=useId();return <Field><div className="flex items-center gap-1"><FieldLabel htmlFor={id}>{label}</FieldLabel>{help&&<FieldHelp>{help}</FieldHelp>}</div>{step==='0.01'?<CurrencyInput id={id} aria-label={label} placeholder="0.00" value={value?String(value):''} onValueChange={amount=>onChange(Number(amount))}/>:<Input id={id} aria-label={label} type="number" min="0" step={step} value={value||''} onChange={e=>onChange(Number(e.target.value))}/>}</Field>;}
export function InfrastructureEditor(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [draft,setDraft]=useState<InfrastructureInput|null>(null),[editing,setEditing]=useState<InfrastructurePackage|null>(null),[step,setStep]=useState(0),[selected,setSelected]=useState('classroomPri');
 const [profile,setProfile]=useState({male:0,female:0,latitude:'',longitude:''}),[profileDirty,setProfileDirty]=useState(false);
 const [baseline,setBaseline]=useState(''),[pending,setPending]=useState<null|(()=>void)>(null),[remove,setRemove]=useState<InfrastructurePackage|null>(null);
 const lock=useRef(false);
 const load=useCallback(async()=>{const r=await fetch(currentPlanHref('/api/infrastructure/packages'),{cache:'no-store'});const body=await r.json() as Data & {error?:string};if(!r.ok)throw Error(body.error??'Unable to load infrastructure.');setData(body);setError('');},[]);
 useEffect(()=>{void Promise.resolve().then(load).catch(e=>setError(e.message));},[load]);
 const dirty=!!draft&&(JSON.stringify(draft)!==baseline||profileDirty);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const guard=(run:()=>void)=>{if(dirty)setPending(()=>run);else run();};
 const school=editing&&!data?.canEdit?editing.school:data?.schools.find(s=>s.id===draft?.schoolId);
 const enrolment=school?(school.male+school.female):0;
 const result=draft?(editing&&!data?.canEdit?editing.result:calculateInfrastructure(draft,enrolment)):null;
 const gaps=draft?auditGaps(draft,enrolment):[];
 const [removingDocument,setRemovingDocument]=useState<string|null>(null);
 async function removeDocument(){
  if(!removingDocument||lock.current)return;
  lock.current=true;setBusy(true);
  try{
   const url=new URL(currentPlanHref('/api/infrastructure/documents'),window.location.origin);url.searchParams.set('id',removingDocument);
   const response=await fetch(url,{method:'DELETE'});
   const body=await response.json() as {error?:string;packages?:{id:number;version:number}[]};if(!response.ok)throw Error(body.error||'Unable to remove attachment.');
   setDraft(d=>d?{...d,documentIds:d.documentIds.filter(id=>id!==removingDocument)}:d);
   setEditing(e=>{const updated=body.packages?.find((p:{id:number})=>p.id===e?.id);return e&&updated?{...e,version:updated.version}:e;});
   await load();setRemovingDocument(null);toast.success('Attachment removed.');
  }catch(e){toast.error(e instanceof Error?e.message:'Unable to remove attachment.');}
  finally{lock.current=false;setBusy(false);}
 }
 const disabled=busy||!data?.canEdit;
 const patch=(p:Partial<InfrastructureInput>)=>setDraft(d=>d?{...d,...p,...(p.schoolId!==undefined&&p.schoolId!==d.schoolId?{documentIds:[]}:{} )}:d);
 function begin(kind:InfrastructureInput['kind'],record?:InfrastructurePackage){const d=record?structuredClone(record.input):{...blank(kind),schoolId:0};setDraft(d);setBaseline(JSON.stringify(d));setEditing(record??null);setStep(0);setSelected('classroomPri');setProfileDirty(false);const s=data?.schools.find(s=>s.id===d.schoolId);setProfile(s?{male:s.male,female:s.female,latitude:s.latitude,longitude:s.longitude}:{male:0,female:0,latitude:'',longitude:''});}
 async function command(body:object){if(lock.current)return false;lock.current=true;setBusy(true);try{const r=await fetch(currentPlanHref('/api/infrastructure/packages'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json() as {error?:string};if(!r.ok)throw Error(b.error);await load();return true;}catch(e){toast.error(e instanceof Error?e.message:'Unable to save.');return false;}finally{lock.current=false;setBusy(false);}}
 async function upload(kind:InfraDocument['kind'],file?:File){if(!file||lock.current)return;lock.current=true;setBusy(true);try{const form=new FormData();form.set('kind',kind);form.set('file',file);if(kind!=='drawings')form.set('schoolId',String(draft?.schoolId));const r=await fetch(currentPlanHref('/api/infrastructure/documents'),{method:'POST',body:form});const doc=await r.json() as InfraDocument & {error?:string};if(!r.ok)throw Error(doc.error);if(draft)patch({documentIds:[...draft.documentIds,doc.id]});await load();toast.success('Document attached.');}catch(e){toast.error(e instanceof Error?e.message:'Unable to upload.');}finally{lock.current=false;setBusy(false);}}
 function uploader(kind:InfraDocument['kind'],compact=false){return <Field key={kind}><div className="flex items-center gap-1"><FieldLabel htmlFor={'upload-'+kind}>{docLabels[kind]}</FieldLabel>{docHelp[kind]&&<FieldHelp>{docHelp[kind]}</FieldHelp>}</div><FileUpload id={'upload-'+kind} label={docLabels[kind]} accept={documentAccept[kind]} compact={compact} illustration={kind==='boq'||kind==='survey'?kind:undefined} busy={busy} disabled={disabled||(kind!=='drawings'&&!draft?.schoolId)} onFiles={files=>upload(kind,files[0])}/><DocumentFiles compact={compact} disabled={disabled} onRemove={data?.canEdit?id=>setRemovingDocument(id):undefined} documents={(data?.documents??[]).filter(d=>d.kind===kind&&(kind==='drawings'||d.schoolId===draft?.schoolId)).map(d=>({id:d.id,name:d.name,size:d.size,url:'/api/infrastructure/documents?id='+d.id}))}/></Field>;}
 async function save(){if(!draft)return;const parsed=packageSchema.safeParse(draft);if(!parsed.success){toast.error(parsed.error.issues[0].message);return;}const issue=packageProblem(parsed.data,enrolment);if(issue){toast.error(issue);return;}if(await command({action:'save',input:parsed.data,id:editing?.id,version:editing?.version})){setDraft(null);setEditing(null);toast.success('Infrastructure package saved.');}}
 function next(){if(!draft)return;if(step===0&&(!school||(enrolment<=0&&draft.kind!=='furniture')||profileDirty)){toast.error('Select a school and save its enrolment first.');return;}if(step===0&&draft.kind==='new'&&!Object.values(draft.land).every(Boolean)){toast.error('Confirm the three land declarations.');return;}setStep(s=>s+1);setSelected('');}
 const steps=draft?.kind==='whole'?['School','Audit','Gaps','Costing','Review']:draft?.kind==='new'?['School','Targeting','Costing','Review']:['School','Items','Review'];
 const costStep=draft?.kind==='furniture'?1:draft?.kind==='whole'?3:2;
 const editableCostItems=result?.items.filter(i=>draft?.kind==='whole'||!['vat','contingency','preliminaries'].includes(i.key))??[];
 const selectedCost=editableCostItems.find(i=>i.key===selected)??editableCostItems[0];
 const selectedCostIndex=selectedCost?editableCostItems.findIndex(i=>i.key===selectedCost.key):-1;
 const showCostItemNavigation=step===costStep&&draft?.kind!=='furniture'&&!(draft?.kind==='new'&&draft.targeting==='nonhope');
 const previousCostItem=()=>{const previousItem=editableCostItems[selectedCostIndex-1];if(previousItem)setSelected(previousItem.key);};
 const nextCostItem=()=>{const nextItem=editableCostItems[selectedCostIndex+1];if(nextItem)setSelected(nextItem.key);};
 useEffect(()=>{
  if(!showCostItemNavigation||!selectedCost)return;
  const frame=window.requestAnimationFrame(()=>{
   document.querySelector<HTMLElement>(`[data-cost-key="${selectedCost.key}"]`)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest',inline:'nearest'});
  });
  return()=>window.cancelAnimationFrame(frame);
 },[selectedCost?.key,showCostItemNavigation]);
 const selectedGap=gaps.find(i=>i.key===selected)??gaps[0];
 return <div className="portal-shell activity-shell infrastructure-shell"><div className="portal-workspace">
  <header className="workspace-header editor-page-header"><div className="editor-header-heading"><Button variant="ghost" onClick={()=>guard(()=>draft?setDraft(null):window.location.assign(currentPlanHref('/beap')))}><ArrowLeftIcon data-icon="inline-start"/>{draft?'Infrastructure':'Basic Education Action Plan'}</Button><span className="editor-plan-title">{draft?kindNames[draft.kind]:'Infrastructure'}{data?' · '+planPeriod(data.plan):''}</span></div><Button variant="outline" onClick={()=>guard(()=>window.location.assign(currentPlanHref('/beap/review')+'#review-infrastructure'))}>Review & send</Button></header>
  {error&&<Alert variant="destructive"><AlertTitle>Unable to load infrastructure</AlertTitle><AlertDescription>{error}<Button variant="outline" onClick={()=>void load().catch(e=>setError(e.message))}>Retry</Button></AlertDescription></Alert>}
  {!data&&!error&&<p className="p-8">Loading infrastructure…</p>}
  {data&&!draft&&<ScrollArea className="flex-1 min-h-0"><main className="infra-home">
   <div className="flex flex-wrap items-end justify-between gap-4"><div><h1>Infrastructure projects</h1><p className="text-muted-foreground">School packages and supporting documents</p></div><div className="text-right"><p className="text-sm text-muted-foreground">Saved package budget</p><strong className="text-2xl tabular-nums">{money.format(data.packages.reduce((s,p)=>s+Number(p.total_cost),0))}</strong></div></div>
   <div className="infra-choices">{(['new','whole','furniture'] as const).map((kind,i)=>{return <Card key={kind} className="infra-choice" data-kind={kind}><CardHeader><InfrastructureIllustration kind={kind}/><CardTitle>{kindNames[kind]}</CardTitle><CardDescription>{['Build to the school’s model, with HOPE or Non-HOPE funding.','Audit facilities, identify gaps and cost the interventions.','Plan furniture quantities and costs for each school.'][i]}</CardDescription></CardHeader><CardContent><dl className="infra-choice-budget"><dt className="sr-only">Saved budget</dt><dd>{money.format(data.packages.filter(p=>p.kind===kind).reduce((sum,p)=>sum+Number(p.total_cost),0))}</dd></dl><Button className="rounded-full px-5" variant="outline" disabled={disabled} onClick={()=>begin(kind)}><PlusIcon data-icon="inline-start"/>{kind==='whole'?'Start assessment':'Add item'}</Button></CardContent></Card>;})}</div>
   <Card><CardHeader><CardTitle>Saved packages <Badge variant="secondary">{data.packages.length}</Badge></CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>School</TableHead><TableHead>Intervention</TableHead><TableHead>Model</TableHead><TableHead>Budget</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{data.packages.map(p=><TableRow key={p.id}><TableCell className="whitespace-normal"><strong>{p.school.name}</strong><p className="text-muted-foreground">{p.school.lga}</p></TableCell><TableCell><Badge variant="outline" data-role="intervention" data-kind={p.kind}>{kindNames[p.kind]}</Badge></TableCell><TableCell>{p.result.modelLabel}</TableCell><TableCell>{money.format(Number(p.total_cost))}</TableCell><TableCell><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>{begin(p.kind,p);if(!data.canEdit)setStep(p.kind==='furniture'?2:p.kind==='whole'?4:3);}}>{data.canEdit?'Open':'View'}</Button><Button variant="ghost" size="icon" disabled={disabled} aria-label={'Delete package for '+p.school.name} onClick={()=>setRemove(p)}><Trash2Icon/></Button></div></TableCell></TableRow>)}{!data.packages.length&&<TableRow><TableCell colSpan={5}>No school packages yet.</TableCell></TableRow>}</TableBody></Table></CardContent></Card>
   <Card><CardHeader><CardTitle>Drawings</CardTitle><CardDescription>Upload the infrastructure drawings used across this funding plan.</CardDescription></CardHeader><CardContent className="flex flex-col gap-5"><FieldGroup>{uploader('drawings')}</FieldGroup></CardContent></Card>
  </main></ScrollArea>}
  {data&&draft&&result&&<><nav className="infra-steps" aria-label="Package steps">{steps.map((label,i)=><span key={label} aria-current={step===i?'step':undefined}><span>{i+1}</span>{label}</span>)}</nav><div className="activity-split">
   <section className="workspace-pane editor-pane"><ScrollArea className="pane-scroll"><div className="editor-canvas"><h1 className="mb-5 text-xl font-semibold">{steps[step]}</h1>{!data.canEdit&&<Alert><AlertTitle>Read-only</AlertTitle><AlertDescription>This package cannot be edited at its current review stage.</AlertDescription></Alert>}<fieldset disabled={disabled}><FieldGroup className={step===steps.length-1?'infra-review-stack':undefined}>
    {step===0&&<><Field><FieldLabel htmlFor="infra-school">School</FieldLabel><Combobox items={data.schools} value={school??null} onValueChange={(s:InfrastructureSchool|null)=>{patch({schoolId:s?.id??0,grouping:'standard'});setProfile(s?{male:s.male,female:s.female,latitude:s.latitude,longitude:s.longitude}:{male:0,female:0,latitude:'',longitude:''});setProfileDirty(false);}} itemToStringLabel={(s:InfrastructureSchool)=>s.name} itemToStringValue={(s:InfrastructureSchool)=>String(s.id)} isItemEqualToValue={(a,b)=>a.id===b.id}><ComboboxInput id="infra-school" placeholder="Search the state school register…"/><ComboboxContent><ComboboxEmpty>No schools found.</ComboboxEmpty><ComboboxList>{(s:InfrastructureSchool)=><ComboboxItem key={s.id} value={s}>{s.name} · {s.lga}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></Field>
     {school&&<><p className="text-muted-foreground">{school.lga} · {school.level} · {school.location}</p><FieldSet><FieldLegend>School register details</FieldLegend><FieldGroup className="grid grid-cols-2 gap-4"><NumberField label="Male enrolment" value={profile.male} onChange={male=>{setProfile({...profile,male});setProfileDirty(true);}}/><NumberField label="Female enrolment" value={profile.female} onChange={female=>{setProfile({...profile,female});setProfileDirty(true);}}/>{(['latitude','longitude'] as const).map(k=><Field key={k}><FieldLabel>{k==='latitude'?'Latitude':'Longitude'}<Input value={profile[k]} onChange={e=>{setProfile({...profile,[k]:e.target.value});setProfileDirty(true);}}/></FieldLabel></Field>)}</FieldGroup><Button variant="outline" disabled={!profileDirty||disabled} onClick={async()=>{if(await command({action:'profile',schoolId:school.id,profile})){setProfileDirty(false);toast.success('School register updated.');}}}>Save school details</Button></FieldSet><Badge variant="secondary">{enrolment>0?modelNames[modelFor(enrolment)]:'Enrolment needed'} · {enrolment} learners</Badge></>}
     <FieldSet><FieldLegend>School components</FieldLegend><FieldGroup className="flex flex-row flex-wrap gap-5">{(['ECCDE','Primary','JSS'] as const).map(c=><Field key={c} orientation="horizontal"><Checkbox id={'component-'+c} checked={draft.components.includes(c)} onCheckedChange={checked=>patch({components:checked?[...draft.components,c]:draft.components.filter(v=>v!==c)})}/><FieldLabel htmlFor={'component-'+c}>{c}</FieldLabel></Field>)}</FieldGroup></FieldSet>
     {draft.kind==='new'&&<><FieldSet className="land-agreement"><FieldLegend>Land declaration & agreement</FieldLegend><p className="land-agreement-description">By checking each declaration, I confirm that the following is true for this school.</p><FieldGroup>{([['available','Land required for this model is available'],['documented','C of O, R of O or Community Agreement is available'],['unencumbered','The land is free from encumbrances']] as const).map(([key,label])=><Field key={key} orientation="horizontal"><Checkbox id={key} checked={draft.land[key]} onCheckedChange={v=>patch({land:{...draft.land,[key]:v===true}})}/><FieldLabel htmlFor={key}>{label}</FieldLabel></Field>)}</FieldGroup></FieldSet>{uploader('land')}</>}
    </>}
    {step===1&&draft.kind==='new'&&<><SelectField label="Funding targeting" help="Choose whether this package is funded under HOPE or outside HOPE. This changes how construction costs are entered." value={draft.targeting} options={[{value:'hope',label:'HOPE'},{value:'nonhope',label:'Non-HOPE'}]} onChange={v=>patch({targeting:v as 'hope'|'nonhope'})}/><p className="text-muted-foreground">{draft.targeting==='hope'?'Cost the classroom blocks and other requirements individually.':'Enter one lump sum for the complete school construction package.'}</p><SelectField label="Classroom grouping" help="Use Storey only where limited land requires vertical construction; otherwise use Standard." value={draft.grouping} options={[{value:'standard',label:'Standard · sufficient land'},...(modelFor(enrolment)>0?[{value:'storey',label:'Storey · limited land'}]:[])]} onChange={v=>patch({grouping:v as 'standard'|'storey',prices:{}})}/></>}
    {step===1&&draft.kind==='whole'&&selectedGap&&<><SelectField label="Facility to audit" value={selectedGap.key} options={gaps.map(g=>({value:g.key,label:g.label}))} onChange={setSelected}/><p className="text-muted-foreground">Required: {selectedGap.required} {selectedGap.unit}</p>{selectedGap.key==='fence'&&<NumberField label="Fence required (metres)" value={draft.fenceRequired} onChange={fenceRequired=>patch({fenceRequired})}/>}{(['existing','functional','extra'] as const).map(k=><NumberField key={k} label={{existing:'Existing',functional:'Functional',extra:'Extra beyond standard'}[k]} help={{existing:'Total units physically present at the school, whether functional or not.',functional:'Existing units that are safe and usable without rehabilitation.',extra:'Additional units requested above the calculated minimum requirement.'}[k]} value={selectedGap[k]} onChange={v=>patch({audit:{...draft.audit,[selectedGap.key]:{existing:selectedGap.existing,functional:selectedGap.functional,extra:selectedGap.extra,[k]:v}}})}/>)}<p>Non-functional: {selectedGap.nonFunctional} · Additional: {selectedGap.additional}</p><Field><FieldLabel>Site observations<Textarea value={draft.observations} onChange={e=>patch({observations:e.target.value})}/></FieldLabel></Field>{(draft.audit.classroomPri?.existing??0)>(draft.audit.classroomPri?.functional??0)&&<><SelectField label="Extent of dilapidation" help="Choose the condition that best describes the non-functional facilities observed on site." value={draft.dilapidation} options={['Minor repairs required','Moderate deterioration','Unsafe / reconstruction recommended','Severe dilapidation / major rehabilitation'].map(v=>({value:v,label:v}))} onChange={v=>patch({dilapidation:v as InfrastructureInput['dilapidation']})}/><Field><FieldLabel>Structural condition notes<Textarea value={draft.conditionNotes} onChange={e=>patch({conditionNotes:e.target.value})}/></FieldLabel></Field>{uploader('photo')}</>}</>}
    {step===2&&draft.kind==='whole'&&<><h2 className="font-semibold">Situation and gap analysis</h2><p>{gaps.filter(g=>g.toBuild>0||g.nonFunctional>0).length} requirements need intervention.</p><p className="text-muted-foreground">Civil works separate renovation of non-functional facilities from new construction. Other requirements replace shortages in functional units.</p><p>Review the audit and calculated quantities before costing.</p></>}
    {step===costStep&&draft.kind==='new'&&<><SelectField label={draft.targeting==='hope'?'Classroom implementation strategy':'Implementation strategy'} help="Select the approved procurement method for delivering this construction package." value={draft.classroomStrategy} options={strategies.map(v=>({value:v,label:v}))} onChange={v=>patch({classroomStrategy:v as InfrastructureInput['classroomStrategy']})}/>{draft.targeting==='nonhope'?<><NumberField label="Total construction cost (₦)" step="0.01" value={draft.lumpSum} onChange={lumpSum=>patch({lumpSum})}/><Field><FieldLabel>Duration<Input value={draft.duration} placeholder="e.g. 6 months" onChange={e=>patch({duration:e.target.value})}/></FieldLabel></Field></>:<><SelectField label="Requirement to cost" value={selectedCost?.key??''} options={result.items.filter(i=>!['vat','contingency','preliminaries'].includes(i.key)).map(i=>({value:i.key,label:i.label}))} onChange={setSelected}/>{selectedCost&&<><p>{selectedCost.quantity} {selectedCost.unit} · {selectedCost.lump?'Enter the total amount for this row.':'Enter the cost per unit.'}</p><NumberField label={selectedCost.lump?'Amount (₦)':'Unit cost (₦)'} step="0.01" value={draft.prices[selectedCost.key]??0} onChange={v=>patch({prices:{...draft.prices,[selectedCost.key]:v}})}/></>}<NumberField label="Fence length (metres)" value={draft.fenceLength} onChange={fenceLength=>patch({fenceLength})}/><NumberField label="Contingency (₦)" help="Provision for unforeseen costs; enter the approved total amount." step="0.01" value={draft.contingency} onChange={contingency=>patch({contingency})}/><NumberField label="Preliminaries (₦)" help="Site setup, supervision, mobilization and other project-wide preliminary costs." step="0.01" value={draft.preliminaries} onChange={preliminaries=>patch({preliminaries})}/><p className="text-sm text-muted-foreground">VAT: {money.format(result.vat)}. Classroom costs are included in the VAT base only for NCB.</p></>}</>}
    {step===costStep&&draft.kind==='whole'&&selectedCost&&<><SelectField label="Intervention to cost" value={selectedCost.key} options={result.items.map(i=>({value:i.key,label:i.label+' · '+i.operation}))} onChange={setSelected}/><p>{selectedCost.quantity} {selectedCost.unit} · {selectedCost.operation}</p><NumberField label={selectedCost.lump?'Package amount (₦)':'Unit cost (₦)'} step="0.01" value={selectedCost.cost} onChange={cost=>patch({packageCosts:{...draft.packageCosts,[selectedCost.key]:{cost,strategy:selectedCost.strategy as 'NCB',duration:selectedCost.duration}}})}/><SelectField label="Implementation strategy" help="Select the approved procurement method for delivering this intervention." value={selectedCost.strategy} options={strategies.map(v=>({value:v,label:v}))} onChange={v=>patch({packageCosts:{...draft.packageCosts,[selectedCost.key]:{cost:selectedCost.cost,strategy:v as 'NCB',duration:selectedCost.duration}}})}/><Field><FieldLabel>Duration<Input value={selectedCost.duration} placeholder="e.g. 6–10 weeks" onChange={e=>patch({packageCosts:{...draft.packageCosts,[selectedCost.key]:{cost:selectedCost.cost,strategy:selectedCost.strategy as 'NCB',duration:e.target.value}}})}/></FieldLabel></Field></>}
    {step===costStep&&draft.kind==='furniture'&&<>{draft.furniture.map((f,i)=><FieldSet key={i}><FieldLegend>Furniture item {i+1}</FieldLegend><FieldGroup><Field><FieldLabel>Description<Input value={f.description} onChange={e=>patch({furniture:draft.furniture.map((r,n)=>n===i?{...r,description:e.target.value}:r)})}/></FieldLabel></Field><NumberField label="Quantity" value={f.quantity} onChange={quantity=>patch({furniture:draft.furniture.map((r,n)=>n===i?{...r,quantity}:r)})}/><NumberField label="Unit cost (₦)" step="0.01" value={f.cost} onChange={cost=>patch({furniture:draft.furniture.map((r,n)=>n===i?{...r,cost}:r)})}/><Button variant="ghost" onClick={()=>patch({furniture:draft.furniture.filter((_,n)=>n!==i)})}>Remove item</Button></FieldGroup></FieldSet>)}<Button variant="outline" onClick={()=>patch({furniture:[...draft.furniture,{description:'',quantity:1,cost:0}]})}><PlusIcon data-icon="inline-start"/>Add furniture item</Button></>}
    {step===steps.length-1&&<><Alert className="infra-accessibility-note"><AccessibilityIcon/><AlertTitle>Accessible by design</AlertTitle><AlertDescription>Include accessibility provisions in the designs for classrooms, toilets and other facilities.</AlertDescription></Alert>{editing?.kind==='whole'&&<Alert><AlertTitle>Updated BOQ required</AlertTitle><AlertDescription>Attach an updated BOQ to save changes to this school package.</AlertDescription></Alert>}<FieldSet className="infra-review-documents"><FieldLegend>School documents</FieldLegend><FieldGroup>{uploader('boq')}{draft.kind!=='furniture'&&uploader('survey')}</FieldGroup></FieldSet>{packageProblem(draft,enrolment)&&<Alert><AlertTitle>Complete the package</AlertTitle><AlertDescription>{packageProblem(draft,enrolment)}</AlertDescription></Alert>}</>}
   </FieldGroup></fieldset></div></ScrollArea><footer className="editor-footer"><div className="line-total"><span>Package total</span><strong>{money.format(result.total)}</strong></div><div className="footer-actions">{step>0&&<Button variant="outline" disabled={busy} onClick={()=>{setStep(s=>s-1);setSelected('');}}>Back</Button>}{showCostItemNavigation&&<ButtonGroup className="infra-cost-navigation" aria-label="Cost item navigation"><Button size="icon" variant="secondary" aria-label="Previous cost item" title="Previous cost item" disabled={disabled||selectedCostIndex<=0} onClick={previousCostItem}><ChevronLeftIcon/></Button><ButtonGroupSeparator/><Button size="icon" variant="secondary" aria-label="Next cost item" title="Next cost item" disabled={disabled||selectedCostIndex<0||selectedCostIndex===editableCostItems.length-1} onClick={nextCostItem}><ChevronRightIcon/></Button></ButtonGroup>}{step<steps.length-1?<Button disabled={disabled||(step===0&&draft.kind==='new'&&!Object.values(draft.land).every(Boolean))} onClick={next}>Continue<ArrowRightIcon data-icon="inline-end"/></Button>:<Button disabled={disabled} onClick={()=>void save()}>{busy?'Saving…':'Save package'}</Button>}</div></footer></section>
   <section className="workspace-pane preview-pane"><ScrollArea className="pane-scroll"><article className="preview-document sports-preview"><div className="plan-overview"><div><span>{school?.name??'Choose a school'}</span><strong>{money.format(result.total)}</strong></div><p>{enrolment>0?result.modelLabel:'School package preview'}</p></div>
    {!school||(!enrolment&&draft.kind!=='furniture')?<Empty><EmptyHeader><EmptyTitle>Select a school to begin</EmptyTitle><EmptyDescription>Save the enrolment to calculate this school’s model and requirements.</EmptyDescription></EmptyHeader></Empty>:draft.kind==='whole'&&(step===1||step===2)?<Table><TableHeader><TableRow>{['Requirement','Required','Existing','Functional','Non-functional','Additional','Extra',''].map((s,i)=><TableHead key={i}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{gaps.map(g=><TableRow key={g.key} data-state={g.key===selectedGap?.key?'selected':undefined}><TableCell className="whitespace-normal">{g.label}</TableCell><TableCell>{g.required}</TableCell><TableCell>{g.existing}</TableCell><TableCell>{g.functional}</TableCell><TableCell>{g.nonFunctional}</TableCell><TableCell>{g.additional}</TableCell><TableCell>{g.extra}</TableCell><TableCell>{step===1&&<Button size="icon" variant="ghost" aria-label={'Audit '+g.label} onClick={()=>setSelected(g.key)}><PencilIcon/></Button>}</TableCell></TableRow>)}</TableBody></Table>:<>{step===costStep&&draft.kind!=='furniture'&&!(draft.kind==='new'&&draft.targeting==='nonhope')&&<Table className="infra-cost-table" data-kind={draft.kind}><TableHeader><TableRow><TableHead>Requirement</TableHead><TableHead>Quantity</TableHead><TableHead>Amount</TableHead></TableRow></TableHeader><TableBody>{result.items.map(i=>{const editable=editableCostItems.some(item=>item.key===i.key);return <TableRow key={i.key} className={editable?'infra-cost-row':undefined} tabIndex={editable?0:undefined} aria-label={editable?'Edit cost for '+i.label:undefined} aria-selected={editable?i.key===selectedCost?.key:undefined} data-cost-key={editable?i.key:undefined} data-state={i.key===selectedCost?.key?'selected':undefined} onClick={editable?()=>setSelected(i.key):undefined} onKeyDown={editable?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(i.key);}}:undefined}><TableCell className="whitespace-normal">{i.label}{i.operation&&<p className="text-muted-foreground">{i.operation}</p>}</TableCell><TableCell>{i.quantity} {i.unit}</TableCell><TableCell>{money.format(i.total)}</TableCell></TableRow>;})}</TableBody></Table>}{(step!==costStep||draft.kind==='furniture'||draft.targeting==='nonhope')&&<InfrastructurePackageDetails record={{id:editing?.id??0,version:editing?.version??1,kind:draft.kind,input:draft,result,school:school??{id:0,name:'',lga:'',level:'',location:'',male:0,female:0,latitude:'',longitude:''},total_cost:String(result.total)}}/>}</>}
   </article></ScrollArea></section></div></>}
 </div><AlertDialog open={!!pending} onOpenChange={v=>{if(!v)setPending(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard unsaved changes?</AlertDialogTitle><AlertDialogDescription>Your saved packages will remain available.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={()=>{const run=pending;setPending(null);run?.();}}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v&&!busy)setRemove(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this school package?</AlertDialogTitle><AlertDialogDescription>This removes the package from the current working plan. Submitted versions remain in review history.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={async()=>{if(remove&&await command({action:'delete',id:remove.id,version:remove.version}))setRemove(null);}}>Delete package</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!removingDocument} onOpenChange={open=>{if(!open&&!busy)setRemovingDocument(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this attachment?</AlertDialogTitle><AlertDialogDescription>The attachment will be removed from the working plan. Previously submitted versions are preserved. Required documents must be replaced before sending for review.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={busy}>Cancel</AlertDialogCancel><Button variant="destructive" disabled={busy} onClick={()=>void removeDocument()}>{busy?'Removing…':'Remove attachment'}</Button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
